# Generated by Django 4.0.3 on 2022-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('HA', 'Home Applaince'), ('G', 'Grocceory'), ('BW', 'Bottom Wear'), ('TW', 'Top Wear')], max_length=3),
        ),
    ]
